### ISSUE TITLE
Unable to import to Android-Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [PareshMayani/DesignSupportLibraryExamples#1]
This is what I get:

![untitled20150705235503](https://cloud.githubusercontent.com/assets/5357526/8513429/eb0243e2-2373-11e5-97b5-c258b46d7a57.png)

How come?

**Comment by PareshMayani** [comment]
@AndroidDeveloperLB I will check it and fix up the issue. Thanks for reporting it.

**Comment by PareshMayani** [comment]
The issue is you are importing 'DesignSupportLibraryExamples' folder, which is not actually a project, but just a folder contains actual android projects i.e. SnackbarDemo, NavigationViewDemo, etc.

So try importing individual projects.

**Comment by AndroidDeveloperLB** [comment]
Can you please make the whole folder contain multiple runnable projects then?

**Comment by PareshMayani** [comment]
@AndroidDeveloperLB please do it separately as of now, there will be a single project with combining all the design library features.

**Comment by AndroidDeveloperLB** [comment]
Thank you !
